### PR TITLE
Fixing security role logic to handle missing privileges

### PR DESCRIPTION
**Pull request by pdkreid**
modifying logic to allow for priveleges that do not exist to not fail the script

### CODE REVIEW

**Comment by DarthFennec** [comment]
Hm ... isn't

``` groovy
if (not priv.startswith('nx-repository-') and priv in privmap) or priv in privmap:
```

the same as

``` groovy
if priv in privmap:
```

? 

<hr>

If I remember correctly, the idea here was to only filter out autogenerated privileges that didn't exist. If you create a privilege in Nexus and then delete it, it will always (as far as I'm aware) remove that privilege from any roles that use it. However, if you create a repository and privileges are autogenerated for that repository, deleting the repository deletes the privileges, but doesn't remove them from roles. This is a bug in Nexus, and this code prevents said bug from crashing the migrator.

The thing is, I don't know of any other situations where a privilege will be referenced by a role, yet not exist. If I don't know what those situations are (or even if there are any), then I don't know what the right thing to do is in those situations, and I certainly don't know that the right thing is to remove that privilege from the role without notifying the user. The only correct choice is to allow it to fail, until we know for certain what should be done instead.

I wonder why you made this PR? Specifically, did you encounter a crash because of this logic? If so, we can try to discover the source of the problem, which will allow us to decide what the appropriate change should be.

**Comment by pdkreid** [comment]
Here's what I found (and I'm not immediately at my work computer, but can get some additional debug logs once I am). When running the initial configuration, it would consistently fail to read the security settings successfully. 

I added some debug messages, I found that an existing (Nexus-created) role, had 7 privileges tied to it. Something like nx-repository-view-*, then it had 6 "T" priveleges...T1, T2, T3, T4, T5, T6. I found that 3 of those privileges mapped correctly to current privileges that the role had applied (I think T1, T3, and T5 were ok). But T2, T4, and T6 had no privilege in the map. Looking in the Nexus UI, I found the role only had 4 privileges showing, which map to the nx- privilege plus the T1, T3, T5 privileges. So I didn't know of a way to effectively remove the privileges from that role as it didn't appear they should be attached.

What my change would do is verify that any privilege that doesn't start with 'nx-repository-' is available in the privatemap since that would be required in the next line -- and the reason the script failed since T4 wasn't in the map, but it was attempted to be retrieved.

**Comment by pdkreid** [comment]
Attached is the debug log file. I added additional info lines to print the privmap and role so that I could see what the role referenced for privileges and what the privilege map contained (those outputs are at line 69 and 70).

[logfile.txt](https://github.com/jfrog/nexus2artifactory/files/2368395/logfile.txt)

**Comment by DarthFennec** [comment]
I see. This instance was upgraded from Nexus 2, correct? Nexus 2 uses these `T1`, `T2`, etc names to refer to its handful of built-in privileges. They must have been introduced improperly by the upgrade process.

>What my change would do is verify that any privilege that doesn't start with 'nx-repository-' is available in the privatemap since that would be required in the next line -- and the reason the script failed since T4 wasn't in the map, but it was attempted to be retrieved.

The reason the code didn't already do this is because I don't know for a fact that blindly and automatically ignoring these missing privileges is always going to be the right decision. Depending on the situation, assuming a privilege shouldn't exist might be a security problem, and allowing the exception to be thrown during migration is the fastest way to let the user know that something might be wrong, so that's what the current code does in the general case. There is currently one special case when dealing with built-in privileges (which all have names starting with `nx-repository-`) where I know that ignoring is the proper choice, but in general the safest bet is to throw exceptions until more special cases can be included.

>Looking in the Nexus UI, I found the role only had 4 privileges showing, which map to the nx- privilege plus the T1, T3, T5 privileges.

Hm ... that makes me think Nexus is designed to ignore privileges that don't exist, and pretend that roles don't use them. If that's true, your approach would be correct in the general case I think, especially if it turns out that the upgrade process allows broken privileges in general, and it's not some special handling for the built-in ones (the former seems more likely). If that's actually the case, I think I would be okay with accepting this.

<hr>

>What my change would do is verify that any privilege that doesn't start with 'nx-repository-' is available in the privatemap since that would be required in the next line

Your change verifies that privileges that don't start with `nx-repository-` are in the privmap. The original code already verified that privileges that do start with `nx-repository-` are in the privmap. The resulting code just verifies that the privilege is in the privmap, so the following is equivalent:

``` groovy
if priv in privmap:
    privs.append(privmap[priv])
```

**Comment by peters95** [comment]
Closing due to age. Please re-open if necessary.

**Pull request closed without merging**
