### PR TITLE
Adding the possibility to change Maven Snapshot Version Behavior's value

### PR DESCRIPTION
**Pull request by zonArt**
Thanks to @drorb's answer on [StackOverflow](https://stackoverflow.com/a/44667473/5498757), I can now propose this little enhancement
Should also fix the opened issue on the same repo #5

### CODE REVIEW

**Comment by DarthFennec** [comment]
This looks good! I added some of my own changes if you don't mind, just better validation mostly. But I'll merge this now. Thanks!

**Comment by zonArt** [comment]
Excellent, thanks, your commit makes totally sense. Could you maybe have a look at my comment on the chosen letter for the `Max Unique Snaphots` option ?

**Comment by DarthFennec** [comment]
I can't seem to find the comment you're referring to, could you link it to me?

**Comment by zonArt** [comment]
I actually tried to open a review but maybe I did it wrong

**Comment by zonArt** [comment]
https://github.com/JFrogDev/nexus2artifactory/pull/6/files#r124196090

**Comment by DarthFennec** [comment]
You are absolutely correct, I'm not sure how I overlooked that. From the [Artifactory documentation](https://www.jfrog.com/confluence/display/RTF/Repository+Configuration+JSON), it appears that `maxUniqueSnapshots` is supported for local and remote repositories, though `snapshotVersionBehavior` is only supported for local ones. So then, changing the letter seems like the better option. I've gone with <kbd>x</kbd>, like it was in your updated PR. Let me know what you think.

**Comment by zonArt** [comment]
Yes I think changing the letter looks good, what about the same `if` declaration? Is it on purpose or could that be merged in one?

**Comment by DarthFennec** [comment]
It's on purpose. If you notice, there is an `if repo['class'] in ('local', 'remote'):`, followed by an `if repo['class'] == 'local':`, followed by another `if repo['class'] in ('local', 'remote'):`. I can't combine the two duplicate `if`s if I want the behavior option to stay in its original position in the menu. Although, now that I think about it, I suppose the behavior and max snapshots options could be swapped ... I don't see anything wrong with that, but I don't think it's really that important one way or the other. Might as well though. Should be fixed now.

**Pull request merged**
