### PR TITLE
fix: fix duplicate pom files upload

### LINKED ISSUE #62: why upload pom.xml or .pom files after other files?
```python
class Maven(object):
    def __init__(self):
        self.lock = threading.Lock()
        self.poms = []

    def deployPaths(self, localpath, metapath, repo, repopath):
        fname = os.path.basename(repopath)
        if fname == 'pom.xml' or fname.endswith('.pom'):
            pom = localpath, metapath, repo, repopath
            with self.lock: self.poms.append(pom)
            return []
        return [(localpath, metapath, repo, repopath, {})]

    def cleanup(self):
        for localpath, metapath, repo, repopath in self.poms:
            yield localpath, metapath, repo, repopath, {}
```
Since items are only appended to self.poms and never deleted, when I run migration repeatedly, the same pom file will be uploaded multiple times.

### PR DESCRIPTION
**Pull request by AkeemMYU**
Closes: #62

### CODE REVIEW

**Comment by AkeemMYU** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Comment by AkeemMYU** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by AkeemMYU** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by AkeemMYU** [comment]
recheckcla

**Comment by DarthFennec** [comment]
Looks good! Thanks

**Pull request merged**
